server:
  port: 8082
  error:
    whitelabel:
      enabled: false
    path: /error
  servlet:
    context-path: /

spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: postgres
      password: postgres
  mvc:
    servlet:
      path: /
  kafka:
    bootstrap-servers: localhost:9092